spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_management_db
    username: employee_app_user
    password: shahryar
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  #
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    clean-disabled: false

app:
  file:
    upload-dir: uploads/documents
