CREATE TABLE task
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    story_point VARCHAR(50)  NOT NULL,
    status      VARCHAR(50)  NOT NULL,
    due_date    DATE,
    created_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE assignment
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    assigned_by BIGINT NOT NULL,
    assigned_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_assignment_task FOREIGN KEY (task_id) REFERENCES task (id),
    CONSTRAINT fk_assignment_employee FOREIGN KEY (employee_id) REFERENCES employee (id),
    CONSTRAINT fk_assignment_assigned_by FOREIGN KEY (assigned_by) REFERENCES employee (id)
);